services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app/app
      - ./frontend:/app/frontend
    depends_on:
      - frontend
    environment:
      - GROQ_API_KEY=${GROQ_API_KEY}


  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    ports:
      - "80:80"
